version: '3'

volumes:
  kittygram_data:
  static:

services:
  new_db:
    image: postgres:13
    env_file: .env
    volumes:
      - kittygram_data:/var/lib/postgresql/data
  kittygram_backend:
    image: currently/kittygram_backend 
    env_file: .env
    volumes:
      - static:/backend_static
    depends_on: 
      - new_db
  kittygram_frontend:
    env_file: .env
    image: currently/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  kittygram_gateway:
    image: currently/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
    depends_on: 
      - kittygram_backend 
      - kittygram_frontend
