version: '3'

volumes:
  kittygram_data:
  static:

services:
  new_db:
    image: postgres:13
    env_file: .env
    volumes:
      - kittygram_data:/var/lib/postgresql/data
  kittygram_backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
  kittygram_frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  kittygram_gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
